#!/bin/bash

NTP_LOCAL=/etc/ntp.local.conf

if [ ! -f $NTP_LOCAL ]; then
    echo "Error: $NTP_LOCAL does not exist."
    exit 1
fi

DEFAULT_IP="`grep iburst $NTP_LOCAL | awk '{ print $2 }'`"

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    echo "Usage: ntpd-sync-time [-1] [server]"
    echo ""
    echo "Options:"
    echo "   -1       Run the ntpd command only once. By default it runs until "
    echo "              the time is synchronised."
    echo "   server   The server to synchronise with. By default the server in "
    echo "              /etc/ntp.local.conf is used."
    exit 0
fi

/etc/init.d/ntp stop > /dev/null

if [ "$1" == "-1" ]; then
    ONCE=true
    if [ $2 ]; then
        IP=$2
    else
        IP=$DEFAULT_IP
    fi
elif [ $1 ]; then
    ONCE=false
    IP=$1
else
    ONCE=false
    IP=$DEFAULT_IP
fi

sed -i -e "/iburst/{s/$DEFAULT_IP/$IP/}" $NTP_LOCAL

echo "Trying to synchronise clock with $IP, do not interrupt."

c=0
while [ 1 ]; do
    if [[ $c -eq 1 && $ONCE == true ]]; then
        echo -e "Failed to synchronise with $IP"
        exit 1
    fi

    r="`ntpd -gq -c /etc/ntp.local.conf`"
    if [ "$r" != "" ]; then
        echo -e "Synchronised with $IP: ${r:6}"
        echo "Time is now:  `date`"
        break
    fi
    c=`expr $c + 1`
done

sed -i -e "/iburst/{s/$IP/$DEFAULT_IP/}" $NTP_LOCAL

/etc/init.d/ntp start > /dev/null
