#!/bin/bash
### BEGIN INIT INFO
# Provides:          ssh-phone-home
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop ssh connection home
### END INIT INFO-

if [ -f /etc/default/ssh-phone-home ]; then
    . /etc/default/ssh-phone-home
fi

if [[ ! $SSH_HOME_USER || ! $SSH_HOME_HOST ]]; then
    exit 1
fi

if [ "$SSH_OPTIONS" != "" ]; then
    SSH_OPTIONS="-o $SSH_OPTIONS"
fi

HOSTID=`hostname | sed -rn '/^.*[A-Za-z][0-9]{3}/{s/^.*[A-Za-z]([0-9]{3})$/\1/p}'`
if [ "$HOSTID" == "" ]; then
    echo "Not starting ssh connection, bad hostname. Hostname should end with 3 numbers."
    exit 1
fi

start() {
    if [ -f /root/.ssh/id_rsa ]; then
        echo "Starting ssh phone-home connection."
        touch /tmp/ssh-phone-home-enabled
        autossh -M 4${HOSTID}0 -f ${SSH_OPTIONS} -NR 10${HOSTID}:127.0.0.1:22 ${SSH_HOME_USER}@${SSH_HOME_HOST}
    else
        echo "Not starting ssh connection, private key missing."
        exit 1
    fi
}

stop() {
    if [ `ps aux | grep "autossh/autossh" | grep -v grep | wc -l` -gt 0 ]; then
        echo "Stopping ssh phone-home connection."
        if [ -f /tmp/ssh-phone-home-enabled ]; then
            rm /tmp/ssh-phone-home-enabled
        fi
        kill `ps aux | grep "autossh/autossh" | grep -v grep | head -n 1 | awk '{print $2}'`
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
esac
