#!/bin/bash
### BEGIN INIT INFO
# Provides:          ssh-phone-home
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop ssh connection home
### END INIT INFO-

HOSTNAME=`hostname`
HOSTID=${HOSTNAME:6}

start() {
    if [ -f /root/.ssh/id_rsa ]; then
        echo "Starting ssh phone-home connection."
        autossh -M 4${HOSTID}0 -f -NR 10${HOSTID}:127.0.0.1:22 alix@huybr.dyndns.org
    else
        echo "Not starting ssh connection, private key missing."
    fi
}

stop() {
    if [ `ps aux | grep autossh | grep -v grep | wc -l` -gt 0 ]; then
        echo "Stopping ssh phone-home connection."
        kill `ps aux | grep autossh | grep -v grep | head -n 1 | awk '{print $2}'`
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
esac
